### ISSUE TITLE
No module named 'fasterai'

### ISSUE THREAD

**Issue by dhofverberg** [Ichaelus/video-colorization#4]
The software seems very promising and interesting, but unfortunately I haven't been able to get it to work. I think I have installed the software and Deoldify, along with all required modules, but after having installed everything I only get this when I run colorize_video.sh:

> Checking dependencies..
> Removing files from previous video convertions..
> Downloading video in highest resolution and tranforming it to frames..
> Downloading and extracting highest quality audio from original video..
> Colorizing each frame..
> Traceback (most recent call last):
>   File "colorize_frames.py", line 10, in <module>
>     from deoldify.fasterai.visualize import *
>   File "/mnt/c/users/daniel/documents/video-colorization-master/deoldify/fasterai/visualize.py", line 10, in <module>
>     from fasterai.transforms import BlackAndWhiteTransform
> ModuleNotFoundError: No module named 'fasterai'
> Colorizing frames failed

All earlier error messages I have gotten have been pretty easy to resolve, by installing the module mentioned. But what on means "No module named 'fasterai'", and how do I resolve this? There is obviously a directory named 'fasterai' under Deoldify, but there doesn't seem to be any such module possible to install.

I'm sure it's me who's done something wrong, but I can't figure out what. Is there some module I have missed installing, or what does this error message mean?

Currently running Ubuntu 16.04.5, or rather the Ubuntu subset under Windows 10.

**Comment by Ichaelus** [comment]
Hi @dhofverberg,
I'm glad too see people trying out my little project, and eager to help you fix your problem.

I just cloned the repository by scratch and was able to reproduce the issue. The deoldify submodule was not tracking the latest commit of Deoldify and thus did not include a commit of mine to fix the described issue.

Please pull my latest commit and run `git submodule update` to get the video colorization working.

**Comment by dhofverberg** [comment]
Thank you. This seems to resolve that issue.

However, when I now try the script, it says "CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:32".

I was certain my graphics card supported CUDA, but after looking into it more, it seems I was wrong… :(

You mentioned that an old version of your script supported execution via CPU instead of CUDA. How complicated would it be to switch back to CPU? Is it just a matter of changing in a couple of places in the code, or is it a more complicated matter? In this case, I'm not too concerned about speed and don't mind waiting...

**Comment by Ichaelus** [comment]
Hi again,
the error message suggests that your graphic cards _does_ support CUDA, but is running on an older version that required by torch. 
Could you first try to update your CUDA driver version? Maybe this link will help you out on this:
https://stackoverflow.com/a/55351774

My first attempts with this project were actually running solely on a CPU, so basically it would be possible. The drawback is however that DeOldify has no support for it out of the box, so you have to [modify their code](https://github.com/jantic/DeOldify/pull/60/commits/0d735972754472a0a42213b4c028b92ee1515bb2) (as well). If you are not successful on upgrading CUDA, I'll help you get it running on the CPU.
An old branch suggesting CPU support is this one: https://github.com/Ichaelus/video-colorization/tree/cpu-support . However, I think it won't work out of the box.
